### ISSUE TITLE
Login screen design 

### ISSUE THREAD

**Issue by riyazhdholakia** [AgaKhanFoundation/WCF-iOS#156]
review marvel https://marvelapp.com/5c70c7a/screen/54473078 (on boarding)

![IMG_4968](https://user-images.githubusercontent.com/33207542/57228250-57085780-6fe1-11e9-811c-81d9071119d3.png)
^my screenshot from a 7 plus

the akf logo is cut(hidden)
terms and conditions is not correctly typed

@compnerd

**Comment by compnerd** [comment]
Its not hidden - it is missing - need to actually get the image to add it.
