### ISSUE TITLE
Onboarding Tour

### ISSUE THREAD

**Issue by riyazhdholakia** [AgaKhanFoundation/WCF-iOS#158]
1. it skips the screenshot attached (this is pulled from marvel https://marvelapp.com/5c70c7a/screen/54473078 (onboarding)

2. 2nd and 3rd screenshot from marvel. the two images seem to be off in sizing (i am running the app on a 7 plus)

![Screen Shot 2019-05-06 at 9 40 24 AM](https://user-images.githubusercontent.com/33207542/57229215-84560500-6fe3-11e9-91ad-49be4f4dee83.png)
![Screen Shot 2019-05-06 at 9 42 54 AM](https://user-images.githubusercontent.com/33207542/57229216-84560500-6fe3-11e9-919f-694145d27433.png)
![Screen Shot 2019-05-06 at 9 42 59 AM](https://user-images.githubusercontent.com/33207542/57229220-88822280-6fe3-11e9-89b9-d3071ade0ad7.png)

**Comment by riyazhdholakia** [comment]
@compnerd

**Comment by compnerd** [comment]
Yes, the original images didn't scale well for some reason.  Perhaps you can figure out hot to scale them to the correct resolution?
