### ISSUE TITLE
Dashboard design 

### ISSUE THREAD

**Issue by riyazhdholakia** [AgaKhanFoundation/WCF-iOS#160]
1. Screen shots are attached from a 7 plus device 
https://marvelapp.com/5c70c7a/screen/54473078 (Click Dashboard)

@compnerd 
![IMG_4971](https://user-images.githubusercontent.com/33207542/57229372-e6166f00-6fe3-11e9-8ef3-f792f826d74b.png)
![IMG_4970](https://user-images.githubusercontent.com/33207542/57229373-e6af0580-6fe3-11e9-969b-b34a4e88bb39.png)

**Comment by compnerd** [comment]
The dashboard was redesigned and needs to be reimplemented.
