### ISSUE TITLE
Fix constraints for setting toggle cell

### ISSUE THREAD

**Issue by samisuteria** [AgaKhanFoundation/WCF-iOS#241]
![simulator_screen_shot_-_iphone_se_-_2019-09-23_at_22 30 16](https://user-images.githubusercontent.com/1434903/65653562-a10ecb80-dfca-11e9-8133-9410c07d0973.png)

"Can you move the text “your team…” below the toggle such that its taking up the width of the entire container?
only for smaller screens that is"

**Comment by jayson528** [comment]
hey, id like to work on this as well if thats okay.
