### ISSUE TITLE
team view for members

### ISSUE THREAD

**Issue by noureend** [AgaKhanFoundation/WCF-iOS#279]
Currently, members cannot see the list of team members in settings.
Add: list of team members and say "Lead" next to the lead's name
Remove: invite members list and delete team button
marvel: https://marvelapp.com/5c70c7a/screen/55754084

**Current state**
![image](https://user-images.githubusercontent.com/9322407/66249586-4cbac880-e6fb-11e9-9e95-367154c408b9.png)

**Expected state**
![image](https://user-images.githubusercontent.com/9322407/66249598-8be91980-e6fb-11e9-8fc3-8f000579ad46.png)

**Comment by compnerd** [comment]
@noureend not sure what is happening here:
<img width="538" alt="image" src="https://user-images.githubusercontent.com/63311/66260047-474a9600-e76e-11e9-9f5b-e99cbcb8829b.png">
