### ISSUE TITLE
Share Badges

### ISSUE THREAD

**Issue by faridmerchant** [AgaKhanFoundation/WCF-iOS#320]
1. As a user, i should be able to share the badges i have achieved
2. An indication on this screen that badges can be shared
https://marvelapp.com/4f66egg/screen/55433626
3. I could share the badges either via text, email, instagram, facebook etc
https://marvelapp.com/4f66egg/screen/55454348
https://marvelapp.com/4f66egg/screen/55454349
4. We should create a customize message for each badge that they can share.
https://marvelapp.com/4f66egg/screen/55505773

**Comment by riyazhdholakia** [comment]
test
