### ISSUE TITLE
Devices not connected

### ISSUE THREAD

**Issue by faridmerchant** [AgaKhanFoundation/WCF-iOS#398]
After I connected my health device (health kit) and then I reconnected using iPhone but setting shows "connect device"

Also when I click on open setting it took me to settings not matching with what was stated in instructions 

See screenshots ![image](https://user-images.githubusercontent.com/26264204/88489137-5beb5b00-cf47-11ea-8bff-ab33bffe3250.png)
![image](https://user-images.githubusercontent.com/26264204/88489138-60b00f00-cf47-11ea-9662-f32803344a35.png)
![image](https://user-images.githubusercontent.com/26264204/88489141-6574c300-cf47-11ea-9f7a-5fb84b13a894.png)
![image](https://user-images.githubusercontent.com/26264204/88489148-6c9bd100-cf47-11ea-9ec4-99008a6d52ed.png)

**Comment by amulji** [comment]
@samisuteria Can you look into this.
