### ISSUE TITLE
Not able to create team

### ISSUE THREAD

**Issue by faridmerchant** [AgaKhanFoundation/WCF-iOS#399]
When I create a team name it gives me error

![image](https://user-images.githubusercontent.com/26264204/88489233-f481db00-cf47-11ea-85dc-316d3e38fcf9.png)

**Comment by aalimmulji** [comment]
@faridmerchant Its seems to be working fine. This error message appears when you trying to use a name that is already been taken. Can you try with a different name

**Comment by aalimmulji** [comment]
Issue no more reproducable
