### ISSUE TITLE
configure build buddy to not perform builds on branch creation

### ISSUE THREAD

**Issue by compnerd** [AgaKhanFoundation/WCF-iOS#73]

**Comment by samisuteria** [comment]
<img width="759" alt="screenshot 2017-04-23 17 45 57" src="https://cloud.githubusercontent.com/assets/1434903/25318095/ca45cd7e-284c-11e7-957c-c62aba61e759.png">

Builds will only happen on code pushes to PRs now and if theres a pending build on that branch it'll auto-cancel if new code is pushed.
