### ISSUE TITLE
Join a Team: Users can search for a team

### ISSUE THREAD

**Issue by alyshaj** [AgaKhanFoundation/WCF-iOS#99]
When looking for a team to join, users should be able to search for a team by typing the team name and/or the Team Captain's name (ideally). The results list should populate as the user is typing (i.e. with just a partial search term). Each item in the results list should contain: team photo, team name, Team Captain's name, and number of members (+ any other necessary info - maybe we want to add whether the team still has space available or if the team is full?).

**Comment by alyshaj** [comment]
- [ ] Testing task list functionality

**Comment by alyshaj** [comment]
Users can search for a team that they can request to join by typing the team name or team captain's name (latter is TBD). Should see a results list - each item has the team photo, team name, and number of team members (+ maybe some indicator if team is already full).

**Comment by riyazhdholakia** [comment]
We are having a lot issues with the Team, here is an email from a user. I have pinned this it goes hand and hand with our team creating issues. Others should be able to find other teams to join, or invite link to join that team only. 

User via email: "There is a team but it’s not showing and when any one is trying to find the team name it’s showing error. Can you Please check thanks."
User screenshots are attached 
![image3](https://user-images.githubusercontent.com/33207542/65783274-77b28480-e11d-11e9-8b99-bc1455726456.png)
![image2](https://user-images.githubusercontent.com/33207542/65783280-797c4800-e11d-11e9-8e15-424f8291b6db.png)

**Comment by samisuteria** [comment]
Should be fixed with: https://github.com/AgaKhanFoundation/WCF-iOS/pull/286

If someone is seeing no teams at all - its because they are not a part of an event. They are added to the first event when the account is created.
